---
abstract: 'Interface to the UPS tracking webservice'
author:
  - 'Maroš Kollár'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-UPS-Tracking
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime: 0.44
  Encode: 0
  Exception::Class: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Getopt: 0
  Path::Class: 0
  Text::SimpleTable: 0
  XML::LibXML: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/maros/Business-UPS-Tracking.git
version: 1.060
